version: '3.8'
services:
  service-db:
    image: postgres:15-alpine3.19
    env_file:
      - service-db.env
    networks:
      - dock_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

#  backend:
#    image: backend:0.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      service-db:
#        condition: service_healthy
#    ports:
#      - ${PORT_APP}:8080
#    networks:
#      - dock_net
#    env_file:
#      - backend.env

volumes:
  db-data:

networks:
  dock_net:
    driver: bridge